project:
  type: book
  output-dir: docs

book:
  title: "CMS Certification Numbers"
  author: "Andrew Allen Bruce"
  date: "12/24/2025"
  back-to-top-navigation: true
  page-navigation: true
  page-footer: "Â© Copyright 2026 Andrew Allen Bruce."
  site-url: https://andrewallenbruce.github.io/ccn_notes/
  repo-url: https://github.com/andrewallenbruce/ccn_notes
  chapters:
    - index.qmd
    - intro.qmd
    - location.qmd
    - part: provider.qmd
      chapters:
        - opo.qmd
        - emergency.qmd
        - hha.qmd
        - esrd.qmd
        - cah.qmd
    - part: medicaid.qmd
      chapters:
        - nf.qmd
        - icf.qmd
        - moh.qmd
    - part: eipps.qmd
      chapters:
        - unit.qmd
        - subunit.qmd
    - part: supplier.qmd
      chapters:
        - asc.qmd
        - clia.qmd
        - pxrf.qmd
  appendices:
    - resources.qmd

format:
  html:
    theme:
      - lumen
      - brand
    date: last-modified
    code-link: true
    code-fold: false
    code-tools: true
    embed-resources: false
    toc: true



